#!/usr/bin/env bash

green() {
    printf "\e[0;32m%s\e[0m" "$1"
}

install() {
    echo $(green "Downloading Jira Aliases script...")
    curl -L#o /var/tmp/gg_$$ https://raw.githubusercontent.com/csi-lk/jira-aliases/main/bin/ja
    echo $(green "Setting permissions...")
    chmod -v +x /var/tmp/ja_$$
    echo $(green "Moving to \$PATH")
    sudo mv -fv /var/tmp/ja_$$ /usr/local/bin/ja
    echo $(green "Successfully installed, running setup")
    ja -h
}

install
