#!/usr/bin/env bash

grey() {
    printf "\e[0;90m%s\e[0m" "$1"
}

green() {
    printf "\e[0;32m%s\e[0m" "$1"
}

red() {
    printf "\e[1;31m%s\e[0m" "$1"
}

yellow() {
    printf "\e[0;33m%s\e[0m" "$1"
}

blue() {
    printf "\e[0;36m%s\e[0m" "$1"
}
